import '../Categories/Cards.dart';
import 'Home.dart';
import 'package:flutter/material.dart';

class DataCat4 extends StatelessWidget {
  const DataCat4({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
          centerTitle: true,
          title: Text("Drilling",style: TextStyle(fontStyle: FontStyle.italic, fontSize: 25),),
          backgroundColor: Color.fromRGBO(41, 111, 113, 1),
          leading: IconButton(
            onPressed: (){
              Navigator.pop(context, MaterialPageRoute(builder: ((context)=>Home())));
            },
            icon: Icon(Icons.keyboard_backspace, size: 40,),
          )
      ),
      body: Center(
        child: Padding(
          padding: const EdgeInsets.all(8.0),
          child: SingleChildScrollView(
            child: Column(
              children: [
                Data(
                    image:"assets/16.PNG",
                    Name: "SIS-L124.050.R",
                    Des: "(HW Through Hole Drill BIT S=10X24 D=5X37 RH)",
                    DesA: "بنطة تخريم 5مم يمين نفادي طويلة إنتـاج الشركـة الإيطـالية",
                    DescA: "",
                    Price: "220 L.E",
                    color: Color.fromRGBO(41, 111, 113, 1)),
                SizedBox(height: 20,),
                Data(
                    image:"assets/17.PNG",
                    Name: "SIS-L124.050.L",
                    Des: "(HW Through Hole Drill BIT S=10X24 D=5X37 LH)",
                    DesA: "بنطة تخريم 5مم شمال نفادي طويلة إنتـاج الشركـة الإيطـالية",
                    DescA: "",
                    Price: "220 L.E",
                    color: Color.fromRGBO(41, 111, 113, 1)),
                SizedBox(height: 20,),
                Data(
                    image:"assets/18.PNG",
                    Name: "SIS-L124.080.L",
                    Des: "(HW Through Hole Drill S=10X24 D=8X37 LH)",
                    DesA: "بنطة تخريم 8مم شمال نفادي طويلة إنتـاج الشركـة الإيطـالية",
                    DescA: "",
                    Price: "240 L.E",
                    color: Color.fromRGBO(41, 111, 113, 1)),
                SizedBox(height: 20,),
                Data(
                    image:"assets/19.PNG",
                    Name: "SIS-L124.080.R",
                    Des: "(HW Through Hole Drill S=10X24 D=8X37 RH)",
                    DesA: "بنطة تخريم 8مم يمين نفادي طويلة إنتـاج الشركـة الإيطـالية",
                    DescA: "",
                    Price: "240 L.E",
                    color: Color.fromRGBO(41, 111, 113, 1)),
                SizedBox(height: 20,),
                Data(
                    image:"assets/20.PNG",
                    Name: "SIS-L141.150.L",
                    Des: "(Hinge Boring Bit S=10X26 D=15 Z=2+2 LH)",
                    DesA: "بنطة تخريم 15مم شمال طويلة إنتـاج الشركـة الإيطـالية",
                    DescA: "",
                    Price: "365 L.E",
                    color: Color.fromRGBO(41, 111, 113, 1)),
                SizedBox(height: 20,),
                Data(
                    image:"assets/21.PNG",
                    Name: "SIS-L141.150.R",
                    Des: "(Hinge Boring Bit S=10X26 D=15 Z=2+2 RH)",
                    DesA: "بنطة تخريم 15مم يمين طويلة إنتـاج الشركـة الإيطـالية",
                    DescA: "",
                    Price: "365 L.E",
                    color: Color.fromRGBO(41, 111, 113, 1)),
                SizedBox(height: 20,),
                Data(
                    image:"assets/22.PNG",
                    Name: "SIS-L141.200.L",
                    Des: "(Hinge Boring Bit S=10X26 D=20 Z=2+2 LH)",
                    DesA: "بنطة تخريم 200مم شمال طويلة إنتـاج الشركـة الإيطـالية",
                    DescA: "",
                    Price: "390 L.E",
                    color: Color.fromRGBO(41, 111, 113, 1)),
                SizedBox(height: 20,),
                Data(
                    image:"assets/23.PNG",
                    Name: "SIS-L141.200.R",
                    Des: "(Hinge Boring Bit S=10X26 D=20 Z=2+2 RH)",
                    DesA: "بنطة تخريم 200مم يمين طويلة إنتـاج الشركـة الإيطـالية",
                    DescA: "",
                    Price: "390 L.E",
                    color: Color.fromRGBO(41, 111, 113, 1)),
                SizedBox(height: 20,),
                Data(
                    image:"assets/24.PNG",
                    Name: "SIS-L141.350.L",
                    Des: "(Hinge Boring Bit S=10X26 D=35 Z=2+2 LH)",
                    DesA: "بنطه تخريم 35مم شمال ×70مم – أنتاج إيطالى",
                    DescA: "",
                    Price: "415 L.E",
                    color: Color.fromRGBO(41, 111, 113, 1)),
                SizedBox(height: 20,),
                Data(
                    image:"assets/25.PNG",
                    Name: "SIS-L141.350.R",
                    Des: "(Hinge Boring Bit S=10X26 D=35 Z=2+2 RH)",
                    DesA: "بنطه تخريم 35مم يمين ×70مم – أنتاج إيطالى",
                    DescA: "",
                    Price: "415 L.E",
                    color: Color.fromRGBO(41, 111, 113, 1)),
                SizedBox(height: 20,),
                Data(
                    image:"assets/26.PNG",
                    Name: "SIS-L107.050.L",
                    Des: "(Dowel Drill S=10X30 D=5X35X70 Z2 LH)",
                    DesA: "بنطه تخريم 5مم شمال ×70مم – أنتاج إيطالى",
                    DescA: "",
                    Price: "115 L.E",
                    color: Color.fromRGBO(41, 111, 113, 1)),
                SizedBox(height: 20,),
                Data(
                    image:"assets/27.PNG",
                    Name: "SIS-L107.050.R",
                    Des: "(Dowel Drill S=10X30 D=5X35X70 Z2 RH)",
                    DesA: "بنطه تخريم 5مم يمين ×70مم – أنتاج إيطالى",
                    DescA: "",
                    Price: "115 L.E",
                    color: Color.fromRGBO(41, 111, 113, 1)),
                SizedBox(height: 20,),
                Data(
                    image:"assets/28.PNG",
                    Name: "SIS-L107.080.L",
                    Des: "(Dowel Drill S=10X30 D=8X35X70 Z2 LH)",
                    DesA: "بنطه تخريم 8مم شمال ×70مم – أنتاج إيطالى",
                    DescA: "",
                    Price: "195 L.E",
                    color: Color.fromRGBO(41, 111, 113, 1)),
                SizedBox(height: 20,),
                Data(
                    image:"assets/29.PNG",
                    Name: "SIS-L107.080.R",
                    Des: "(Dowel Drill S=10X30 D=8X35X70 Z2 RH)",
                    DesA: "بنطه تخريم 8مم يمين ×70مم – أنتاج إيطالى",
                    DescA: "",
                    Price: "195 L.E",
                    color: Color.fromRGBO(41, 111, 113, 1)),
                SizedBox(height: 20,),
                Data(
                    image:"assets/30.PNG",
                    Name: "SIS-L107.090.R",
                    Des: "(Dowel Drill S=10X30 D=9X35X70 Z2 RH)",
                    DesA: "بنطة تخريم 9مم يمين طويلة إنتـاج الشركـة الإيطـالية",
                    DescA: "",
                    Price: "270 L.E",
                    color: Color.fromRGBO(41, 111, 113, 1)),
                SizedBox(height: 20,),
                Data(
                    image:"assets/31.PNG",
                    Name: "SIS-L107.100.L",
                    Des: "(Dowel Drill S=10X30 D=10X35X70 Z2 LH)",
                    DesA: "بنطه تخريم 10مم شمال ×70مم – أنتاج إيطالى",
                    DescA: "",
                    Price: "210 L.E",
                    color: Color.fromRGBO(41, 111, 113, 1)),
                SizedBox(height: 20,),
                Data(
                    image:"assets/32.PNG",
                    Name: "SIS-L107.100.R",
                    Des: "( Dowel Drill S=10X30 D=10X35X70 Z2 RH)",
                    DesA: "بنطه تخريم 10مم يمين ×70مم – أنتاج إيطالى",
                    DescA: "",
                    Price: "210 L.E",
                    color: Color.fromRGBO(41, 111, 113, 1)),
                SizedBox(height: 20,),
                Data(
                    image:"assets/33.PNG",
                    Name: "SIS-L107.130.L",
                    Des: "(Dowel Drill S=10X30 D=13X35X70 Z2 LH)",
                    DesA: "بنطة تخريم 13مم شمال طويلة إنتـاج الشركـة الإيطـالية",
                    DescA: "",
                    Price: "375 L.E",
                    color: Color.fromRGBO(41, 111, 113, 1)),
                SizedBox(height: 20,),
                Data(
                    image:"assets/34.PNG",
                    Name: "SIS-L107.130.R",
                    Des: "(Dowel Drill S=10X30 D=13X35X70 Z2 RH)",
                    DesA: "بنطة تخريم 13مم يمين طويلة إنتـاج الشركـة الإيطـالية",
                    DescA: "",
                    Price: "375 L.E",
                    color: Color.fromRGBO(41, 111, 113, 1)),
                SizedBox(height: 20,),
                Data(
                    image:"assets/35.PNG",
                    Name: "SIS-L107.140.L",
                    Des: "( Dowel Drill S=10X30 D=14X35X70 Z2 LH)",
                    DesA: "بنطه تخريم 14مم شمال ×70مم – أنتاج إيطالى",
                    DescA: "",
                    Price: "350 L.E",
                    color: Color.fromRGBO(41, 111, 113, 1)),
                SizedBox(height: 20,),
                Data(
                    image:"assets/36.PNG",
                    Name: "SIS-L107.140.R",
                    Des: "(Dowel Drill S=10X30 D=14X35X70 Z2 RH)",
                    DesA: "بنطه تخريم 14مم يمين ×70مم – أنتاج إيطالى",
                    DescA: "",
                    Price: "350 L.E",
                    color: Color.fromRGBO(41, 111, 113, 1)),
                SizedBox(height: 20,),
                Data(
                    image:"assets/37.PNG",
                    Name: "SIS-T152.061.R",
                    Des: "(Finishing Cutter D=6X27 Z2 RH/DOWN CUT)",
                    DesA: "بنطة راوتر حلزونى 6×27 مم – فيديا – أعلى - الطول 70 مم – 2 ريشة – كعب 6 مم – أنتاج إيطالى",
                    DescA: "",
                    Price: "325 L.E",
                    color: Color.fromRGBO(41, 111, 113, 1)),
                SizedBox(height: 20,),
                Data(
                    image:"assets/38.PNG",
                    Name: "SIS-T152.081.R",
                    Des: "( Finishing Cutter D=8X35 Z2 RH/DOWN CUT)",
                    DesA: "بنطة راوتر حلزونى 8×35 مم – فيديا – أعلى - الطول 80 مم – 2 ريشة – كعب 8 مم – أنتاج إيطالى",
                    DescA: "",
                    Price: "385 L.E",
                    color: Color.fromRGBO(41, 111, 113, 1)),
                SizedBox(height: 20,),
                Data(
                    image:"assets/39.PNG",
                    Name: "SIS-T152.100.R",
                    Des: "(Finishing Cutter D=10X35 Z2 RH/DOWN CUT)",
                    DesA: "بنطة راوتر حلزونى 10×35 مم – فيديا – أعلى - الطول 100 مم – 2 ريشة – كعب 10 مم – أنتاج إيطالى",
                    DescA: "",
                    Price: "375 L.E",
                    color: Color.fromRGBO(41, 111, 113, 1)),
                SizedBox(height: 20,),
                Data(
                    image:"assets/40.PNG",
                    Name: "SIS-S202.081.R",
                    Des: "(SP Slot Mortising Bit+Chipbreaker RH Long.EX S=16X50 D=8X130 Z=2)",
                    DesA: "بنطة منقار عادى 8 مم – صلب – يمين – الطول 130 مم – 2 ريشة - كعب 16×50 مم – أنتاج إيطالى",
                    DescA: "",
                    Price: "330 L.E",
                    color: Color.fromRGBO(41, 111, 113, 1)),
                SizedBox(height: 20,),
                Data(
                    image:"assets/41.PNG",
                    Name: "SIS-S202.101.R",
                    Des: "(SP Slot Mortizing Bit+Chipbreaker RH Long.EX S=16X50 D=10X140 Z=2 DX)",
                    DesA: "بنطة منقار عادى 10 مم – صلب – يمين – الطول 140 مم – 2 ريشة - كعب 16×50 مم – أنتاج إيطالى",
                    DescA: "",
                    Price: "335 L.E",
                    color: Color.fromRGBO(41, 111, 113, 1)),
                SizedBox(height: 20,),
                Data(
                    image:"assets/42.PNG",
                    Name: "SIS-S202.121.R",
                    Des: "(SP Slot Mortising Bit+Chipbreaker RH Long.EX S=16X50 D=12X150 Z=2 DX)",
                    DesA: "بنطة منقار عادى 12 مم – صلب – يمين – الطول 150 مم – 2 ريشة - كعب 16×50 مم – أنتاج إيطالى",
                    DescA: "",
                    Price: "350 L.E",
                    color: Color.fromRGBO(41, 111, 113, 1)),
                SizedBox(height: 20,),
                Data(
                    image:"assets/43.PNG",
                    Name: "SIS-S202.141.R",
                    Des: "(SP Slot Mortising Bit+Chipbreaker RH Long.EX S=16X50 D=14X160 Z=2 DX)",
                    DesA: "بنطة منقار عادى 14 مم – صلب – يمين – الطول 160 مم – 2 ريشة - كعب 16×50 مم – أنتاج إيطالى",
                    DescA: "",
                    Price: "340 L.E",
                    color: Color.fromRGBO(41, 111, 113, 1)),
                SizedBox(height: 20,),
                Data(
                    image:"assets/44.PNG",
                    Name: "SIS-S202.161.R",
                    Des: "(SP Slot Mortising Bit+Chipbreaker RH Long.EX S=16X50 D=16X170 Z=2 DX)",
                    DesA: "بنطة منقار عادى 16 مم – صلب – يمين – الطول 170 مم – 2 ريشة - كعب 16×50 مم – أنتاج إيطالى",
                    DescA: "",
                    Price: "345 L.E",
                    color: Color.fromRGBO(41, 111, 113, 1)),
                SizedBox(height: 20,),
                Data(
                    image:"assets/45.PNG",
                    Name: "SIS-T157.162.R",
                    Des: "(VHW Spiral Cutter D=16X50X100 RH/UP Cut)",
                    DesA: "بنطة روتر 16مم حلزوني للكالون إنتـاج الشركـة الإيطـالية",
                    DescA: "",
                    Price: "2175 L.E",
                    color: Color.fromRGBO(41, 111, 113, 1)),
                SizedBox(height: 20,),
                Data(
                    image:"assets/46.PNG",
                    Name: "SIS-D103.121.R",
                    Des: "(HW Straight Bit S=12 D=12X45 Z=2+1 RH)",
                    DesA: "بنطة روتر 12مم إنتـاج الشركـة الإيطـالية",
                    DescA: "",
                    Price: "600 L.E",
                    color: Color.fromRGBO(41, 111, 113, 1)),
                SizedBox(height: 20,),
                Data(
                    image:"assets/47.PNG",
                    Name: "SIS-T144.081.R",
                    Des: "(Roughing Cutter D=8X35 Z3 RH/UP cut)",
                    DesA: "بنطة روتر حلزوني مشرشر 8مم – أنتاج إيطالى",
                    DescA: "",
                    Price: "725 L.E",
                    color: Color.fromRGBO(41, 111, 113, 1)),
                SizedBox(height: 20,),
                Data(
                    image:"assets/48.PNG",
                    Name: "SIS-T119.040.N",
                    Des: "(Spring Collet ER32 (DIN 6499) d=4-3)",
                    DesA: "كوليت 4مم Er 32 انتـاج الشركـة الإيطـالية",
                    DescA: "",
                    Price: "200 L.E",
                    color: Color.fromRGBO(41, 111, 113, 1)),
                SizedBox(height: 20,),
                Data(
                    image:"assets/49.PNG",
                    Name: "SIS-T119.060.N",
                    Des: "(Spring Collet ER32 (DIN 6499) d=6-5)",
                    DesA: "كوليت من 5-6 مم ER 32 إنتـاج الشركـة الإيطـالية",
                    DescA: "",
                    Price: "200 L.E",
                    color: Color.fromRGBO(41, 111, 113, 1)),
                SizedBox(height: 20,),
                Data(
                    image:"assets/50.PNG",
                    Name: "SIS-T119.120.N",
                    Des: "(Spring Collet ER32 (DIN 6499) d=12-11)",
                    DesA: "كــولـــت راوتـــــر 12 مم ER 32   إنتـاج الشركـة الإيطـالية",
                    DescA: "",
                    Price: "210 L.E",
                    color: Color.fromRGBO(41, 111, 113, 1)),
                SizedBox(height: 20,),
                Data(
                    image:"assets/51.PNG",
                    Name: "SIS-T119.080.N",
                    Des: "(Spring Collet ER32 (DIN 6499) d=8-7)",
                    DesA: "كوليت من 8-7مم ER 32  إنتـاج الشركـة الإيطـالية",
                    DescA: "",
                    Price: "220 L.E",
                    color: Color.fromRGBO(41, 111, 113, 1)),
                SizedBox(height: 20,),
                Data(
                    image:"assets/52.PNG",
                    Name: "SIS-C101.060.R",
                    Des: "(VHW Straight Bit S=8 D=6X19 Z=2+1 RH)",
                    DesA: "بنطة روتر عدل 6مم كعب 8مم إنتـاج الشركـة الإيطـالية",
                    DescA: "",
                    Price: "275 L.E",
                    color: Color.fromRGBO(41, 111, 113, 1)),
                SizedBox(height: 20,),
                Data(
                    image:"assets/53.PNG",
                    Name: "SIS-C101.080.R",
                    Des: "(VHW Straight Bit S=8 D=8X19 Z=2+1 RH)",
                    DesA: "بنطة روتر عدل 8مم كعب 8مم إنتـاج الشركـة الإيطـالية",
                    DescA: "",
                    Price: "275 L.E",
                    color: Color.fromRGBO(41, 111, 113, 1)),
                SizedBox(height: 20,),
                Data(
                    image:"assets/54.PNG",
                    Name: "SIS-T152.060.R",
                    Des: "(VHW Finishing Cutter D=6X17 Z2 RH/Down cut)",
                    DesA: "بنطة راوتر حلزونى 6×17 مم – فيديا – أعلى - الطول 70 مم – 2 ريشة – كعب 6 مم – أنتاج إيطالى",
                    DescA: "",
                    Price: "300 L.E",
                    color: Color.fromRGBO(41, 111, 113, 1)),
                SizedBox(height: 20,),
                Data(
                    image:"assets/55.PNG",
                    Name: "SIS-C109.160.R",
                    Des: "(HW V-Groove Bit S=8 D=16X13 90° Z=2 RH)",
                    DesA: "بنطة راوتر حرف V  فيديا 90 درجة يمين – أنتاج إيطالى",
                    DescA: "",
                    Price: "350 L.E",
                    color: Color.fromRGBO(41, 111, 113, 1)),
                SizedBox(height: 20,),
                Data(
                    image:"assets/56.PNG",
                    Name: "SIS-X502.182.R",
                    Des: "(DP Router Bit S=20X50 D=18X43 Z=5+1 RH)",
                    DesA: "بنطة روتر الماظ 18مم طويلة إنتـاج الشركـة الإيطـالية",
                    DescA: "",
                    Price: "2500 L.E",
                    color: Color.fromRGBO(41, 111, 113, 1)),
                SizedBox(height: 20,),
                Data(
                    image:"assets/57.PNG",
                    Name: "SIS-X501.161.R",
                    Des: "(DP Router Bit S=16X45 D=16X34 Z=4+1 RH)",
                    DesA: "بنطة روتر الماظ 16مم طويلة إنتـاج الشركـة الإيطـالية",
                    DescA: "",
                    Price: "1400 L.E",
                    color: Color.fromRGBO(41, 111, 113, 1)),
                SizedBox(height: 20,),
                Data(
                    image:"assets/58.PNG",
                    Name: "SIS-C101.040.R",
                    Des: "(VHW Straight Bit S=8 D=4X11 Z=2+1 RH)",
                    DesA: "بنطة راوتر 4 مم فيديا عدل يمين – أنتاج إيطالى",
                    DescA: "",
                    Price: "280 L.E",
                    color: Color.fromRGBO(41, 111, 113, 1)),
                SizedBox(height: 20,),
                Data(
                    image:"assets/59.PNG",
                    Name: "SIS-T118.976.R",
                    Des: "(TOOL HOLDER HSK 63F HSK 63F A=75 D=50 X ER 32 DX)",
                    DesA: "هولدر لماكينة الروتر إنتـاج الشركـة الإيطـالية",
                    DescA: "",
                    Price: "1200 L.E",
                    color: Color.fromRGBO(41, 111, 113, 1)),
              ],
            )
          ),
        ),
      ),
    );
  }
}
